= Keycloak Dockerimage with service discovery via KUBE_PING

This image is based on the latest https://github.com/jboss-dockerfiles/keycloak/tree/master/server[Keycloak Dockerimage^] `4.7.0.Final` 
and https://search.maven.org/artifact/org.jgroups.kubernetes/jgroups-kubernetes/1.0.9.Final/jar[jgroups-kubernetes-1.0.9.Final^] library which provides the `KUBE_PING`
service discovery mechanism.

== Patches to the original Keycloak Dockerimage

Upgraded jgroups-kuberntes version from 1.0.6 to 1.0.9.

Adjusted the `=` to `=>` substitution mechanism in `tools/jgroups.sh` to be more flexible.
`:=` is now replaced to `=` to support labels, e.g.:

[source]
-----
port_range=1,namespace=default,labels=app:=keycloak,foo:=bar,masterHost=kubernetes.default.svc,masterPort=443
-----

will result in:

[source]
-----
port_range=>1,namespace=>default,labels=>app=keycloak,foo=bar,masterHost=>kubernetes.default.svc,masterPort=>443
-----

== Build the Dockerimage
[source,bash]
-----
docker build -t thomasdarimont/keycloak-kubeping:latest .
-----

== Dockerimage Options

The following environment variables can be configured:

* `KUBERNETES_NAMESPACE default`

The Kubernetes namespace to use.

* `KUBERNETES_SERVICE_HOST kubernetes.$KUBERNETES_NAMESPACE.svc`

The name of the Kubernetes API server.

* `KUBERNETES_SERVICE_PORT 443`

The port of the Kubernetes API server.


* `KUBERNETES_LABELS "app:=keycloak"`

The comma separated list of labels. Note that `:=` is replaced with `=`.

* `JGROUPS_DISCOVERY_PROPERTIES "port_range=1,namespace=$KUBERNETES_NAMESPACE,labels=$KUBERNETES_LABELS,masterHost=$KUBERNETES_SERVICE_HOST,masterPort=$KUBERNETES_SERVICE_PORT"`

The JGROUPS discovery options.

==== Configure Kubernetes serviceaccount for KUBE_PING

You need to associate your PODs with the `serviceAccountName: keycloak-kubeping-service-account`
such that `KUBE_PING` can discover the other Keycloak nodes in the cluster.

The Kubernetes Service configuration adapted from https://github.com/jgroups-extras/jgroups-kubernetes/tree/master[jgroups-extras/jgroups-kubernetes^].

[source,bash]
-----
# ---------------------------------------------------------------------
# This demo assumes that RBAC is enabled on the Kubernetes cluster.
#
# The serviceaccount, clusterrole and clusterrolebinding provide
# permission for the pods to query K8S api
# ---------------------------------------------------------------------

# Change to a Kubernetes namespace of your preference
export TARGET_NAMESPACE=default

kubectl create serviceaccount keycloak-kubeping-service-account -n $TARGET_NAMESPACE

cat <<EOF | kubectl apply -f -
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: keycloak-kubeping-pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: keycloak-kubeping-api-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keycloak-kubeping-pod-reader
subjects:
- kind: ServiceAccount
  name: keycloak-kubeping-service-account
  namespace: $TARGET_NAMESPACE

EOF
-----